[project]
src = "src"
out = "out"
dot_env = ".env"
name = "cow-forwarder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["snekmate==0.1.2"]
default_network_name = "mainnet-fork"


[networks.mainnet-fork]
url = "${MAINNET_RPC_URL}"
explorer_uri = "https://api.etherscan.com/api/"
explorer_type = "etherscan"
explorer_api_key = "${ETHERSCAN_TOKEN}"
chain_id = 1
fork = true


[networks.mainnet]
url = "${MAINNET_RPC_URL}"
explorer_uri = "https://api.etherscan.io/v2/api"
explorer_type = "etherscan"
explorer_api_key = "${ETHERSCAN_TOKEN}"
chain_id = 1
fork = false
default_account_name = "gramsci"


[networks.arbitrum]
url = "${ARBITRUM_RPC_URL}"
explorer_uri = "https://api.etherscan.io/v2/api"
explorer_type = "etherscan"
explorer_api_key = "${ETHERSCAN_TOKEN}"
chain_id = 42161
fork = false
default_account_name = "gramsci"


[networks.arbitrum-fork]
url = "${ARBITRUM_RPC_URL}"
explorer_uri = "https://api.etherscan.io/v2/api"
explorer_type = "etherscan"
explorer_api_key = "${ETHERSCAN_TOKEN}"
chain_id = 42161
fork = true


[networks.gnosis]
url = "${GNOSIS_RPC_URL}"
explorer_uri = "https://api.etherscan.io/v2/api"
explorer_type = "etherscan"
explorer_api_key = "${ETHERSCAN_TOKEN}"
chain_id = 100
fork = false
default_account_name = "gramsci"


[networks.gnosis-fork]
url = "${GNOSIS_RPC_URL}"
explorer_uri = "https://api.etherscan.io/v2/api"
explorer_type = "etherscan"
explorer_api_key = "${ETHERSCAN_TOKEN}"
chain_id = 100
fork = true


[networks.sepolia]
url = "${SEPOLIA_RPC_URL}"
explorer_uri = "https://api.etherscan.io/v2/api"
explorer_type = "etherscan"
explorer_api_key = "${ETHERSCAN_TOKEN}"
chain_id = 11155111
fork = false
default_account_name = "gramsci"


[networks.sepolia-fork]
url = "${SEPOLIA_RPC_URL}"
explorer_uri = "https://api.etherscan.io/v2/api"
explorer_type = "etherscan"
explorer_api_key = "${ETHERSCAN_TOKEN}"
chain_id = 11155111
fork = true

[tool.isort]
profile = "black"

[tool.natrix]
files = ["src/"]
disabled_rules = ["NTX4", "NTX9", "NTX5"]
